name:                lambda-untyped
version:             0.1.0.0
github:              "nobsun/lambda-untyped"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@gmail.com"
copyright:           "Copyright: (c) 2018 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/lambda-cube#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show >= 0.1.0.2
- markdown-unlit >= 0.5.0
- transformers >= 0.5.2
- pretty >= 1.1.3
- free >= 5.0
- recursion-schemes >= 5.0

library:
  source-dirs: src

executables:
  lambda-untyped:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-untyped

tests:
  lambda-untyped-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-untyped
